Improved getDeviceById query
dojot/backstage pull request #107
Opened 2021-11-24 19:38 UTC by luisfelipefurlan

* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
improvement

* **What is the current behavior?** (You can also link to an open issue here)
getDeviceById returns few fields

* **What is the new behavior (if this is a feature change)?**

added more fields to the device

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

* **Is there any issue related to this PR in other repository?** (such as dojot/dojot)
dojot/dojot#2358

* **Other information**:

2021-11-25 13:29 UTC, LuanEdCosta requested changes

2021-11-25 13:29 UTC, LuanEdCosta commented on src/operations/device/query.getDeviceById.js
> +          isDynamic: attr.type === 'dynamic',
I think that just return the `attr.type` here would be better 🤔
It can be done in the other queries too, but in other PRs.

2021-11-26 16:50 UTC, cfrancisco approved these changes

2021-11-30 17:28 UTC, LuanEdCosta requested changes

2021-11-30 17:28 UTC, LuanEdCosta commented on src/operations/device/query.getDeviceById.js
> +          isDynamic: attr.type,
I would change the `isDynamic` attribute to just `type`. It makes more sense.

2021-11-30 20:33 UTC, LuanEdCosta approved these changes

2021-11-30 20:36 UTC, merged