Issue#2494: disassociate device on delete
dojot/backstage pull request #125
Opened 2022-02-15 12:59 UTC by LeonamMoura

* **Please check if the PR fulfills these requirements**
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
feature

* **What is the current behavior?** (You can also link to an open issue here)
dojot/dojot#2494

* **What is the new behavior (if this is a feature change)?**
On delete a device, the device is disassociated of the certificate.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Is there any issue related to this PR in other repository?** (such as dojot/dojot)

* **Other information**:

2022-02-18 16:32 UTC, LuanEdCosta requested changes

2022-02-18 16:32 UTC, LuanEdCosta commented on src/operations/device/mutation.deleteDevices.js
> +      Promise.all(disassociateLinkedCertificates);
Missing `await` here

2022-02-18 17:08 UTC, LuanEdCosta approved these changes

2022-03-09 17:27 UTC, luisfelipefurlan approved these changes

2022-05-25 16:56 UTC, merged