Removed the widget identification from the OperationType attribute
dojot/backstage pull request #89
Opened 2021-04-22 16:59 UTC by luisfelipefurlan

* **Please check if the PR fulfills these requirements**
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Feat

* **What is the current behavior?** (You can also link to an open issue here)

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Is there any issue related to this PR in other repository?** (such as dojot/dojot)
dojot/dojot#1982

* **Other information**:

2021-04-22 17:09 UTC, mprevide commented
I need add this on  https://github.com/dojot/backstage/pull/88

2021-05-04 13:26 UTC, cfrancisco approved these changes

2021-05-07 14:40 UTC, mprevide commented
Create the same PR to feature/keycloak

2021-05-07 14:41 UTC, mprevide requested changes
Create the same PR to feature/keycloak

2021-05-12 20:19 UTC, mprevide approved these changes

2021-05-13 12:43 UTC, merged